name: OWASP ZAP DAST Scan

on:
  workflow_dispatch:  # Allows manual triggering
  push:
    branches: [ main ]

jobs:
  dast-scan:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.10'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          pip install gunicorn

      - name: Run Flask app with Gunicorn
        run: |
          # Adjust this command based on your actual app structure:
          # If your app factory is in flaskblog/__init__.py
          gunicorn -b 0.0.0.0:5000 app:app &
          
          # Alternative if your app is in app.py:
          # gunicorn -b 127.0.0.0:5000 app:app &

      - name: Wait for application to start
        run: |
          sleep 10
          curl --retry 5 --retry-delay 3 --retry-all-errors http://localhost:5000 || true

      - name: Run OWASP ZAP Full Scan
        uses: zaproxy/action-full-scan@v0.12.0
        with:
          target: 'http://127.0.0.1:5000/'
          fail_action: false  # Don't fail build on findings, just report
          cmd_options: '-a'   # Generate detailed report

      - name: Upload ZAP Report as Artifact
        uses: actions/upload-artifact@v4
        with:
          name: zap-dast-report
          path: zap_report.html
