name: OWASP ZAP DAST Security Scan

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

permissions:
  contents: write
  pages: write
  id-token: write
  actions: read

jobs:
  zap-dast-scan:
    runs-on: ubuntu-latest

    steps:
      # -------------------------------
      # Checkout repo
      # -------------------------------
      - name: Checkout code
        uses: actions/checkout@v4

      # -------------------------------
      # Set up Python
      # -------------------------------
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      # -------------------------------
      # Install dependencies and setup
      # -------------------------------
      - name: Install Python dependencies
        run: pip install -r requirements.txt gunicorn

      # -------------------------------
      # Initialize database
      # -------------------------------
      - name: Initialize database
        run: python init_db.py

      # -------------------------------
      # Start Flask app using Gunicorn
      # -------------------------------
      - name: Start Flask blog
        run: |
          gunicorn -w 2 -b 0.0.0.0:8080 app:app &
          # wait until server is up and responding
          for i in {1..30}; do
            if curl -f http://localhost:8080/ > /dev/null 2>&1; then
              echo "Flask started and responding"
              break
            fi
            echo "Waiting for Flask to start... ($i/30)"
            sleep 2
          done
          # Test the endpoint
          curl -I http://localhost:8080/ || echo "Warning: App may not be fully ready"

      # -------------------------------
      # Prepare ZAP workspace
      # -------------------------------
      # - name: Prepare ZAP working folder
      #   run: mkdir -p /zap/wrk
      

      # -------------------------------
      # Run OWASP ZAP Baseline Scan
      # -------------------------------
      - name: Run OWASP ZAP Scan
        uses: zaproxy/action-baseline@v0.11.0
        continue-on-error: true
        with:
          target: 'http://localhost:8080/'
          cmd_options: "-a"
          fail_action: false
          allow_issue_writing: false
        env:
          GITHUB_TOKEN: ''
          
      # -------------------------------
      # Upload as artifacts
      # -------------------------------
      - name: Upload ZAP Report as Artifact
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: zap-security-report
          path: zap_report/
          retention-days: 30
