name: OWASP ZAP DAST Scan

on:
  workflow_dispatch:  # Allows manual triggering
  push:
    branches: [ main ]

jobs:
  dast-scan:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.10'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          pip install gunicorn

      - name: Run Flask app with Gunicorn
        run: |
          # Use 127.0.0.1 instead of 0.0.0.0 for security
          gunicorn -b 127.0.0.1:5000 app:app &

      - name: Wait for application to start
        run: |
          sleep 5
          echo "Testing application health..."
          curl --retry 10 --retry-delay 3 --retry-all-errors http://127.0.0.1:5000 || echo "Health check failed, but continuing..."

      - name: Run OWASP ZAP Full Scan
        uses: zaproxy/action-full-scan@v0.12.0
        with:
          target: 'http://127.0.0.1:5000'  # Must match Gunicorn binding
          fail_action: false
          cmd_options: '-a'

      - name: Upload ZAP Report as Artifact
        uses: actions/upload-artifact@v4
        with:
          name: zap-dast-report
          path: zap_report.html
