name: OWASP ZAP DAST Scan

on:
  push:
    branches:
      - main

jobs:
  dast-scan:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.10'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          pip install gunicorn

      - name: Run Flask application
        run: |
          export FLASK_APP=app.py
          flask run --host=127.0.0.1 --port=5000 &
          sleep 10  # wait for app startup

      - name: Wait for the application to start
        run: sleep 10

      - name: OWASP ZAP Full Scan with Report Artifact
        uses: zaproxy/action-full-scan@v0.12.0
        with:
          target: 'https://github.com/AugustusNnamdi/thecyberform.git'
          fail_action: false
          artifact_name: 'zap_dast_report' # Custom name for the artifact
