name: Cyberforum Blog CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.10'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt


    - name: Run Flask app
      env:
        FLASK_APP: app.py  # Change this if your main file is different
        FLASK_ENV: development
      run: |
        flask run --host=0.0.0.0 --port=5000 &
        sleep 10  # Give the server time to start
        curl http://localhost:5000  # Test the endpoint

    - name: Run tests
      run: |
        pytest || echo "No tests found"

  # Optional: Deploy job (e.g., to Heroku, AWS, etc.)
  # deploy:
  #   runs-on: ubuntu-latest
  #   needs: build-and-test
  #   steps:
  #     - name: Deploy to server
  #       run: echo "Add your deployment steps here"
