name: Cyberforum Security Scan

on:
  pull_request:
    branches: [ main, master ]
  push:
    branches: [ main, master ]

jobs:
  security-scan:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.x'

      - name: Install Bandit
        run: pip install bandit

      - name: Run Bandit Security Scan
        run: |
          bandit -r . -f txt -o bandit-report.txt
          bandit -r . -f html -o bandit-report.html

      - name: Check for vulnerable dependencies
        run: |
          pip install safety
          safety check -r requirements.txt

      - name: Upload Security Reports
        uses: actions/upload-artifact@v4
        with:
          name: security-reports
          path: |
            bandit-report.txt
            bandit-report.html
