name: Cyberforum Blog Security CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build-and-test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Run SAST (Bandit)
        run: |
          bandit -r . -f txt -o bandit-report.txt || echo "Bandit completed with issues"
        continue-on-error: true

      - name: Upload Bandit report
        uses: actions/upload-artifact@v4
        with:
          name: bandit-report
          path: bandit-report.txt

      - name: Run tests
        run: |
          pytest || echo "No tests found"

      - name: Upload Pytest report
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: pytest-report
          path: tests/test-results/

      - name: Create zap-reports directory
        run: mkdir -p zap-reports

      - name: Run OWASP ZAP Baseline Scan
        uses: zaproxy/action-baseline@v0.10.0
        with:
          target: 'http://localhost:8000'  # Replace with your app's URL
          format: 'txt'
          output: 'zap-reports/zap-report.txt'
        continue-on-error: true

      - name: Upload ZAP TXT report
        uses: actions/upload-artifact@v4
        with:
          name: zap-report-txt
          path: zap-reports/zap-report.txt

