name: Security Analysis Scans

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  sast-bandit:
    name: Static Analysis with Bandit
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.10'

    - name: Install Bandit
      run: |
        python -m pip install --upgrade pip
        pip install bandit

    - name: Run Bandit scan
      run: |
        bandit -r . -lll -o bandit_report.txt

    - name: Upload Bandit report
      uses: actions/upload-artifact@v4
      with:
        name: bandit-report
        path: bandit_report.txt

  dast-owasp-zap:
    name: Dynamic Analysis with OWASP ZAP
    runs-on: ubuntu-latest
    needs: sast-bandit

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Start Flask app
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
        nohup flask run --host=0.0.0.0 --port=5000 &
        sleep 10

    - name: Run OWASP ZAP baseline scan
      uses: zaproxy/action-baseline@v0.10.0
      with:
        target: 'http://localhost:5000'

    - name: Upload ZAP report
      uses: actions/upload-artifact@v4
      with:
        name: zap-report
        path: report_html.html