name: Cyberforum Blog Security CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  bandit-sast:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          pip install bandit

      - name: Install dependencies
        run: pip install -r requirements.txt

      # 1. Bandit: Security linter for Python (finds common vulnerabilities)
      - name: Run Bandit (Python SAST)
        run: |
          pip install bandit
          bandit -r . -f html -o bandit_report.html || true # Run even if it finds issues
        continue-on-error: true # Don't fail the whole job, report
